### ISSUE TITLE
Model file

### ISSUE THREAD

**Issue by Zumbalamambo** [chaosmail/cvsp-age-gender-classification-16#1]
I use cpu. It is hard to create model file. Can you please share your pretrained model file?

**Comment by pakwan** [comment]
Sorry for the late reply. 
Training a CNN without a GPU is absolutely no fun...
So I uploaded a zip containing everything you need to classify images (including the model file) here:
https://drive.google.com/file/d/0B4wx2k8f2Iw7bGRsZklndElwV28/view?usp=sharing
