### ISSUE TITLE
Testing the model file in realtime

### ISSUE THREAD

**Issue by Zumbalamambo** [chaosmail/cvsp-age-gender-classification-16#2]
How do I test the model in a real time video to recognize the gender

**Comment by pakwan** [comment]
This is not the purpose of the software. But you can extend it to do this by feeding the model single frames of the image. As the model expects cropped input images, only showing the faces of people, you also have to do face detection before feeding it to the model. I recommend doing this preprocessing using suited python libraries (e.g. scikit-image,...).
